FROM quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-21 AS builder

WORKDIR /code

COPY .mvn/ .mvn/
COPY mvnw pom.xml ./
COPY src/ src/

RUN sh mvnw -B -ntp package -Pnative -DskipTests

FROM registry.access.redhat.com/ubi9/ubi-micro:latest

WORKDIR /work/
COPY --from=builder /code/target/*-runner /work/application

EXPOSE 8080
USER 1001

ENTRYPOINT ["./application", "-Dquarkus.http.host=0.0.0.0"]